apiVersion: apps/v1
kind: Deployment
metadata:
  name: accident
  labels:
    app: accident
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accident
  template:
    metadata:
      labels:
        app: accident
    spec:
      containers:
        - name: accident
          image: "username/accident:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
